/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package gui;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import tools.*;

/**
 *
 * @author MSI
 */
public class Authentication extends javax.swing.JFrame {
    
    Connection connection = null;       
    ResultSet rs = null;                
    ResultSet rs2 = null;
    PreparedStatement ps = null;
    EncryptPassword encryptPwd;
    
    //------------ Cosnstructor ----------
    public Authentication() throws SQLException, ClassNotFoundException {
        initComponents();
        this.errorLbl.setVisible(false);
        
        //--------- Connect to DB
        connection = ConnectionManager.getConnection();
    
        
        //----- Adjust Window
        Dimension screenSize,frameSize;
        int x,y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize=getSize();
        x=(screenSize.width-frameSize.width)/2;
        y=(screenSize.height-frameSize.height)/2;
        setLocation(x, y);
        
        this.setResizable(false); 

        Image icon = Toolkit.getDefaultToolkit().getImage(Authentication.class.getResource("/images/g1.png"));  
        this.setIconImage(icon);   
        
        this.setTitle("Log In");
    }

    
    //------------ Cosnstructor with arguments ----------
    public Authentication(String email, String password) throws SQLException, ClassNotFoundException {
        initComponents();
        this.emailTxt.setText(email);
        this.passwordTxt.setText(password);
        this.errorLbl.setVisible(false);
        
        //--------- Connect to DB
        connection = ConnectionManager.getConnection();
        
        //----- Adjust Window
        Dimension screenSize,frameSize;
        int x,y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize=getSize();
        x=(screenSize.width-frameSize.width)/2;
        y=(screenSize.height-frameSize.height)/2;
        setLocation(x, y);
        
        this.setResizable(false);
        
        Image icon = Toolkit.getDefaultToolkit().getImage(Authentication.class.getResource("/images/g1.png"));  
        this.setIconImage(icon);   
        
        this.setTitle("Authentification");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        emailLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        connexionBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();
        inscrireBtn = new javax.swing.JButton();
        emailTxt = new javax.swing.JTextField();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");

        contentPanel.setBackground(new java.awt.Color(255, 204, 204));
        contentPanel.setForeground(new java.awt.Color(255, 204, 204));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 255, 255));
        emailLbl.setText("Email");
        contentPanel.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 102, 41));

        passwordLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordLbl.setText("Password");
        contentPanel.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 150, 42));

        titleLbl.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 102, 153));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Log In");
        contentPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 700, 79));

        passwordTxt.setBackground(new java.awt.Color(250, 249, 241));
        passwordTxt.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        passwordTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contentPanel.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 245, 42));

        connexionBtn.setBackground(new java.awt.Color(255, 102, 153));
        connexionBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        connexionBtn.setForeground(new java.awt.Color(255, 255, 255));
        connexionBtn.setText("Log In");
        connexionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionBtnActionPerformed(evt);
            }
        });
        contentPanel.add(connexionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 90, 41));

        errorLbl.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLbl.setText("Password or Email are incorrect!");
        contentPanel.add(errorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 254, 47));

        inscrireBtn.setBackground(new java.awt.Color(255, 102, 153));
        inscrireBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        inscrireBtn.setForeground(new java.awt.Color(255, 255, 255));
        inscrireBtn.setText("Sign In");
        inscrireBtn.setActionCommand("");
        inscrireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireBtnActionPerformed(evt);
            }
        });
        contentPanel.add(inscrireBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 90, 41));

        emailTxt.setBackground(new java.awt.Color(250, 249, 241));
        emailTxt.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        contentPanel.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 245, 45));

        exit.setBackground(new java.awt.Color(225, 7, 14));
        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.setToolTipText("");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        contentPanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    
    //------------ Registration Button ----------
    private void inscrireBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
 
        try {
            Registration in = new Registration();
            in.setVisible(true);
        this.dispose();
        } catch (SQLException ex) {
            
            Logger.getLogger(Authentication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Authentication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                           

    
    //------------ Authentication Button ----------
    private void connexionBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
        int idUser = 0;
        String email = this.emailTxt.getText();
        String password = this.passwordTxt.getText();
                
        try {
            try {
                encryptPwd = new EncryptPassword();
            } catch (Exception ex) {
                Logger.getLogger(Authentication.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            /*******************************************************************
             * The player id is retrieved from the database 
             * if all the information entered by the player are correct
             ******************************************************************/
            ps = connection.prepareStatement("Select id_user from user where email=? and password=?");
            ps.setString(1, email);
            ps.setString(2, encryptPwd.encrypt(password));
            rs = ps.executeQuery(); 
            
            
            while(this.rs.next()) {
                
                //------ retrieve user id 
                idUser = this.rs.getInt(1);
                
                dispose(); 
                
                errorLbl.setVisible(false);
                
                //store the user Id in a Home attribute
                Home.idUser = idUser;
                
                Home home = new Home();
                home.setVisible(true);

                break;
            }
            errorLbl.setVisible(true);
                        
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Authentication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                            

    //------------ Exit Button ----------
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose(); 
    }                                    

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Authentication().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Authentication.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Authentication.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton connexionBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JButton exit;
    private javax.swing.JButton inscrireBtn;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration                   
}
