/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package tools;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author MSI
 */
public class Cell extends javax.swing.JPanel{
    
    public static int TAILLE_CELL = 30;
    private int x; 
    private int y;
    private Stone stone;
    
    //------------ Cosnstructor ----------
    public Cell(int x, int y) {
        initComponents();
        this.x = x;
        this.y = y;
        setPreferredSize(new Dimension(30, 30));
    }
    
    
    //-------- Getters & Setters ----------
    public void setX(int x) {
        this.x = x;
    }
    
    public void setY(int y) {
        this.y = y;
    }
    
    public Stone getStone() {
        return this.stone;
    }
    
    public void setStone(Stone stone) {
        this.stone = stone;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setBackground(new java.awt.Color(255, 102, 153));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    //------- Draw a stone in the board with a given color ------------
    public void drawStone(Color color) {
        stone = new Stone(color);
        this.repaint();
    }
    
    //------- Remove a stone from the board ------------
    public void removeStone() {
        stone = null;
        this.repaint();
    }
    
    //-------- paint the cell ----------
    @Override
    public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        super.paint(g2d);
        if(stone != null)
            stone.drawStone((Graphics2D) g);
        else
        {
            Stone epion = new Stone(new Color(255, 102, 153));
            epion.drawStone((Graphics2D) g);
        }
    }             
}
